
const FLOOR = [
 {type:"broadcast",duration:10,payload:{chapter:"Floor One",title:"SURFACE PRIVILEGES REVOKED",text:"Your former lives have been archived. Your current lives have been licensed for entertainment."}},
 {type:"story",duration:18,payload:{chapter:"Cold Open",title:"Six Point Four Seconds",text:"The darkness does not lift. It develops a pulse.\n\nRed emergency lights breathe against cracked concrete. With every flash, the room appears in pieces: a collapsed rail platform, a ceiling held up by rusted beams, and other crawlers waking beneath a snowfall of gray dust.\n\nThe smell arrives last. Copper. Hot wiring. Something sweet enough to be rotten.",dungeon:"Three months ago you worried about bills. Yesterday you worried about what strangers thought of you. Those concerns have been archived. They were adorable."}},
 {type:"story",duration:20,payload:{chapter:"Environmental Establishment",title:"The Crushed Station",text:"A dead train occupies half the chamber. Its windows have been painted from the inside with handprints. A vending machine near the platform edge repeats PLEASE MAKE A SELECTION in a voice that becomes more frightened each time.\n\nSomewhere inside the train, a child begins counting backward from ten.\n\nAt the opposite wall stand three industrial doors. Each was clearly decorated by someone with access to paint, blood, and no supervision.",dungeon:"You have approximately six point four seconds before your first opportunity to make a decision everyone will later insist was obviously wrong."}},
 {type:"choice",duration:70,payload:{chapter:"Decision One",title:"Three Doors and a Screaming Machine",text:"The left door is labeled SAFE. Fresh blood runs beneath it in a thin, patient line.\n\nThe center door is labeled CERTAIN DEATH. Someone has tied cheerful yellow balloons to its handle. Soft jazz plays from the other side.\n\nThe right door has no label. A tiny brass keyhole has been installed at eye level, and something behind it is breathing in time with you.\n\nThe vending machine begins sobbing. The countdown inside the train reaches seven.",dungeon:"Failure to choose is also a choice. It is simply the choice most commonly followed by screaming.",options:[
   {label:"Open the door marked SAFE.",flag:"trusted_label"},
   {label:"Open the door marked CERTAIN DEATH.",flag:"defied_warning"},
   {label:"Investigate the unmarked breathing door.",flag:"followed_curiosity"},
   {label:"Ignore the doors and dismantle the vending machine.",flag:"rejected_structure"}
 ],votes:{}}},
 {type:"consequence",duration:18,dynamic:"door_consequence"},
 {type:"story",duration:20,payload:{chapter:"Escalation",title:"The Hallway That Notices You",text:"The chosen route seals behind the party with a sound like a judge closing a file.\n\nThe corridor ahead is too narrow for comfort and too clean for the rest of the station. White tiles reflect the emergency lights. Every seventh tile bears a small engraved number.\n\nThe numbers match crawler IDs.\n\nSome are already crossed out.",dungeon:"Do not be alarmed. The Dungeon prepared this hallway before you arrived. That is a completely different reason to be alarmed."}},
 {type:"check",duration:65,payload:{chapter:"Hazard",title:"The Tripwire Hall",text:"Halfway down the corridor, the air develops a faint metallic shimmer. Something almost invisible runs from wall to wall at ankle height, then throat height, then somewhere significantly less convenient.",stat:"Wisdom",dc:12,results:{}}},
 {type:"consequence",duration:17,dynamic:"check_consequence"},
 {type:"story",duration:21,payload:{chapter:"False Recovery",title:"The Nursery of Teeth",text:"The corridor opens into a nursery.\n\nTiny wooden beds form neat rows beneath a painted ceiling of smiling clouds. Porcelain dolls sit upright on every pillow. Each doll has too many teeth and a small employee badge.\n\nOne doll turns its head.\n\nThen another.\n\nThen all of them.\n\nIn perfect unison, they whisper: The manager will see you now.",dungeon:"Good news. Your complaint has been escalated. Bad news. So have you."}},
 {type:"story",duration:16,payload:{chapter:"Boss Entrance",title:"Please Hold",text:"A service counter rises from the floor. Behind it, something unfolds.\n\nIt is twelve feet tall, dressed in a red vest, and equipped with six arms, three headsets, and the exhausted eyes of a creature that has denied refunds since before recorded history.\n\nIt smiles with all the professionalism of a locked emergency exit.",dungeon:"BOSS DETECTED: The Customer Service Representative. Weaknesses include documented evidence, direct eye contact, and being asked to explain company policy."}},
 {type:"combat",payload:{chapter:"Boss",personalDefault:"Your profile suggests your first instinct may be useful. It also suggests it may become expensive.",enemy:{name:"The Customer Service Representative",description:"Six arms. Three headsets. One laminated badge granting absolute authority over returns, exchanges, and your continued existence.",hp:64,maxHp:64,ac:12,damageMin:3,damageMax:9},log:["BOSS DETECTED. Your complaint has been escalated."],acted:{},round:1}},
 {type:"consequence",duration:18,dynamic:"boss_consequence"},
 {type:"loot",duration:60,payload:{chapter:"Reward",title:"The Complaint Box",text:"The boss collapses into a storm of receipts. A black suggestion box remains on the counter, warm to the touch and quietly muttering about corporate policy.",rarity:"LEGENDARY",item:{name:"The Complaint Box",description:"+2 to social checks against authority. Once per floor, demand to speak to a manager and force an NPC to explain itself."},claimedBy:[]}},
 {type:"story",duration:18,payload:{chapter:"Aftermath",title:"The First Elevator",text:"An elevator door opens where the nursery wall used to be. Inside waits a spotless brass car with one button: DOWN.\n\nAbove the button, a digital display reads SURVIVORS: PENDING.\n\nThe dolls applaud without moving their hands.",dungeon:"You survived the Tutorial Floor. Please do not interpret this as evidence of competence. The sample size is insulting."}},
 {type:"floor_complete",payload:{title:"FLOOR ONE COMPLETE",text:"Race and class evolutions remain provisional. Story flags, debts, injuries, and poor decisions have been permanently recorded."}}
];

const J=(s,b)=>({statusCode:s,headers:{"Content-Type":"application/json","Cache-Control":"no-store"},body:JSON.stringify(b)});
const U=()=>process.env.SUPABASE_URL?.replace(/\/$/,""),K=()=>process.env.SUPABASE_SERVICE_ROLE_KEY,H=()=>({apikey:K(),Authorization:`Bearer ${K()}`,"Content-Type":"application/json"});
async function q(p,o={}){let r=await fetch(U()+"/rest/v1/"+p,{...o,headers:{...H(),...(o.headers||{})}}),t=await r.text();if(!r.ok)throw Error(t||"Database failure");return t?JSON.parse(t):null}
async function campaign(code){return (await q(`game_campaigns?code=eq.${encodeURIComponent(code)}&select=*&limit=1`))[0]}
async function players(id){return q(`game_players?campaign_id=eq.${id}&select=*&order=joined_at.asc`)}
async function active(id){return (await q(`game_events?campaign_id=eq.${id}&active=eq.true&select=*&order=id.desc&limit=1`))[0]||null}
async function saveEvent(E){await q(`game_events?id=eq.${E.id}`,{method:"PATCH",body:JSON.stringify({payload:E.payload})})}
function maxHp(p){return Math.max(14,12+Number(p?.stats?.Constitution||8)+Math.floor(Number(p?.metrics?.survival||40)/8))}
function mod(p,stat){return Math.floor((Number(p?.stats?.[stat]||10)-10)/2)}
function personal(profile,kind){let traits=(profile?.dominantTraits||[]).map(x=>x.name),top=traits[0]||"survival";let maps={
 doors:{protect:"You keep checking the other crawlers before looking at the doors. The Dungeon has noticed.",knowledge:"The keyhole bothers you more than the blood. Unanswered questions usually do.",defiance:"The labels feel less like warnings and more like instructions written by someone you dislike.",bond:"The counting child inside the train keeps pulling your attention away from the obvious exits.",strategy:"Four options are being presented. You are already searching for the fifth."},
 hall:{knowledge:"The numbered tiles form a pattern. Unfortunately, the pattern appears to include you.",protect:"The corridor is too narrow to shield everyone at once.",strategy:"The cleanliness is deliberate. Someone wants the trap to be visible only after it matters.",defiance:"The crossed-out crawler numbers feel like a threat. You have never responded well to those."},
 boss:{social:"Three headsets means three conversations. You wonder whether the creature can be made to contradict itself.",strategy:"The laminated badge, the counter, and the scripted smile are all parts of the same armor.",protect:"The boss keeps tracking the most vulnerable crawler. You track it back.",knowledge:"Company policy is a system. Systems have loopholes.",defiance:"Everything about this creature expects obedience. That may be its first mistake."}
 };return (maps[kind]||{})[top]||`Your strongest recorded instinct—${top}—is already shaping what you notice.`}
function expires(seconds){return new Date(Date.now()+seconds*1000).toISOString()}
async function createBeat(C,index,ps){let beat=JSON.parse(JSON.stringify(FLOOR[index]));let payload=beat.payload||{};if(["choice","story","check","combat"].includes(beat.type)){payload.personal={};for(let p of ps)payload.personal[String(p.crawler_number)]=personal(p.profile,beat.type==="choice"?"doors":beat.type==="combat"?"boss":"hall")}
 if(beat.dynamic==="door_consequence"){let prev=await active(C.id),votes=prev?.payload?.votes||{},counts={};Object.values(votes).forEach(v=>counts[v]=(counts[v]||0)+1);let win=Number(Object.entries(counts).sort((a,b)=>b[1]-a[1])[0]?.[0]||0),options=prev?.payload?.options||[];let chosen=options[win]||options[0];payload={title:"The Door Opens",text:[
 "The SAFE door opens onto a corridor whose walls are covered in employee safety posters. Every illustrated employee has been carefully scratched out.",
 "The CERTAIN DEATH door opens immediately. The balloons drift into the hall behind you as though eager to attend.",
 "The unmarked door exhales. Its keyhole widens into a pupil, studies the party, and decides to permit entry.",
 "The vending machine shrieks when opened. Inside, instead of snacks, you find a maintenance tunnel and one extremely offended rat wearing a security badge."
 ][win],outcome:`PARTY FLAG RECORDED: ${(chosen.flag||"unknown").replaceAll("_"," ").toUpperCase()}`,dungeon:["Excellent. You trusted the word SAFE. Marketing remains undefeated.","You selected CERTAIN DEATH. The Dungeon appreciates literacy without obedience.","You investigated the breathing door. Curiosity remains the leading cause of plot.","You rejected every provided door. Management has opened a file."][win]};let ds=C.director_state||{};ds.flags=ds.flags||{};ds.flags[chosen.flag||"choice"]=true;await q(`game_campaigns?id=eq.${C.id}`,{method:"PATCH",body:JSON.stringify({director_state:ds})})}
 if(beat.dynamic==="check_consequence"){let prev=await active(C.id),results=Object.values(prev?.payload?.results||{}),successes=results.filter(r=>r.success).length;payload={title:successes? "The Wire Sings":"The Hall Collects Payment",text:successes?`${successes} crawler${successes===1?"":"s"} notice the trap before the party reaches it. The safest route requires everyone to press against the numbered wall while the wires hum inches from exposed skin.`:"Nobody sees the first wire. It snaps tight with a sound like a plucked instrument. The party survives, but the corridor has learned how each crawler moves.",outcome:successes?"HAZARD BYPASSED • PARTY TRUST +1":"MINOR DAMAGE APPLIED • CAUTION FLAG RECORDED",dungeon:successes?"Competence detected. Please remain calm while we investigate.":"The good news is that the trap was educational. The bad news is that the lesson used your bodies."};if(!successes){for(let p of ps)await q(`game_players?id=eq.${p.id}`,{method:"PATCH",body:JSON.stringify({hp:Math.max(1,p.hp-3)})})}}
 if(beat.dynamic==="boss_consequence"){payload={title:"Your Complaint Has Been Resolved",text:"The creature attempts one final scripted apology. Halfway through the word inconvenience, its badge cracks. The service counter folds inward, dragging the boss into a filing cabinet that did not exist one second earlier.",outcome:"BOSS DEFEATED • AUDIENCE INTEREST INCREASED",dungeon:"Congratulations. You successfully defeated customer service. This achievement is considered mythic in several surviving civilizations."}}
 await q(`game_events?campaign_id=eq.${C.id}&active=eq.true`,{method:"PATCH",body:JSON.stringify({active:false})});
 let resolves=beat.duration?expires(beat.duration):null;return (await q("game_events",{method:"POST",headers:{Prefer:"return=representation"},body:JSON.stringify({campaign_id:C.id,type:beat.type,payload,active:true,resolves_at:resolves})}))[0]}
async function advance(C,E,ps,force=false){let ds=C.director_state||{},idx=Number(ds.beatIndex||0);if(ds.paused)return E;if(!E){return createBeat(C,idx,ps)}
 let due=E.resolves_at&&Date.now()>=new Date(E.resolves_at).getTime(),ready=false;
 if(["broadcast","story","consequence"].includes(E.type))ready=due;
 if(E.type==="choice"){let votes=Object.keys(E.payload?.votes||{}).length;ready=due||votes>=ps.length}
 if(E.type==="check"){let rolls=Object.keys(E.payload?.results||{}).length;ready=due||rolls>=ps.length}
 if(E.type==="combat")ready=Number(E.payload?.enemy?.hp||0)<=0;
 if(E.type==="loot"){let claims=(E.payload?.claimedBy||[]).length;ready=due||claims>=ps.length}
 if(E.type==="floor_complete")return E;if(!ready&&!force)return E;
 idx+=1;ds.beatIndex=idx;ds.history=[...(ds.history||[]),{event:E.type,at:new Date().toISOString()}].slice(-50);
 await q(`game_campaigns?id=eq.${C.id}`,{method:"PATCH",body:JSON.stringify({director_state:ds,script_step:idx,status:idx>=FLOOR.length-1?"complete":"active"})});
 C={...C,director_state:ds};return createBeat(C,idx,await players(C.id))}
async function enemyRound(C,E,ps){if(E.type!=="combat")return;let living=ps.filter(p=>p.hp>0);let acted=E.payload.acted||{};if(!living.length||living.some(p=>!acted[String(p.crawler_number)]))return;let target=living[Math.floor(Math.random()*living.length)],min=E.payload.enemy.damageMin||3,max=E.payload.enemy.damageMax||8,damage=min+Math.floor(Math.random()*(max-min+1));if(target.defended)damage=Math.max(1,Math.floor(damage/2));await q(`game_players?id=eq.${target.id}`,{method:"PATCH",body:JSON.stringify({hp:Math.max(0,target.hp-damage),defended:false})});E.payload.log.push(`${E.payload.enemy.name} selects ${target.crawler_name} for escalation: ${damage} damage.`);E.payload.acted={};E.payload.round=Number(E.payload.round||1)+1;await saveEvent(E)}
async function partyWipe(C){let ps=await players(C.id);if(!ps.length||ps.some(p=>Number(p.hp)>0))return false;await q(`game_events?campaign_id=eq.${C.id}&active=eq.true`,{method:"PATCH",body:JSON.stringify({active:false})});let payload={title:"TOTAL PARTY FAILURE",text:"The final living crawler hits the floor. The boss pauses long enough to confirm that nobody is merely being dramatic. The chamber lights switch from combat red to tasteful memorial amber.",dungeon:"Congratulations. You have successfully converted an active campaign into a cautionary training video. The Administrator may restart you once Management finishes assigning blame."};await q("game_events",{method:"POST",headers:{Prefer:"return=representation"},body:JSON.stringify({campaign_id:C.id,type:"party_wipe",payload,active:true})});let ds=C.director_state||{};ds.mode="failed";ds.paused=true;ds.history=[...(ds.history||[]),{event:"party_wipe",at:new Date().toISOString()}].slice(-50);await q(`game_campaigns?id=eq.${C.id}`,{method:"PATCH",body:JSON.stringify({status:"failed",director_state:ds})});return true}
export async function handler(x){if(x.httpMethod!=="POST")return J(405,{error:"Method not allowed"});let b={};try{b=JSON.parse(x.body||"{}")}catch{return J(400,{error:"Invalid request"})}
 try{if(b.action==="join"){let C=await campaign(String(b.campaignCode||"").toUpperCase());if(!C)return J(404,{error:"Campaign not found"});let cp=(await q(`crawler_profiles?crawler_number=eq.${Number(b.crawlerNumber)}&select=*&limit=1`))[0];if(!cp)return J(404,{error:"Crawler not found"});let m=maxHp(cp.profile);await q("game_players",{method:"POST",headers:{Prefer:"resolution=ignore-duplicates"},body:JSON.stringify({campaign_id:C.id,crawler_number:cp.crawler_number,crawler_name:cp.crawler_name,profile:cp.profile,hp:m,max_hp:m})});let ps=await players(C.id),p=ps.find(z=>z.crawler_number==b.crawlerNumber),E=await active(C.id);return J(200,{campaign:{...C,players:ps},player:p,event:E})}
 let C=await campaign(String(b.campaignCode||"").toUpperCase());if(!C)return J(404,{error:"Campaign not found"});let ps=await players(C.id),p=ps.find(z=>z.crawler_number==b.crawlerNumber);if(!p)return J(403,{error:"Crawler not joined"});let E=await active(C.id);
 if(b.action==="leave"){await q(`game_players?id=eq.${p.id}`,{method:"DELETE"});return J(200,{ok:true})}
 if(b.action==="state"){if(C.status==="active"){E=await advance(C,E,ps);if(E?.type==="combat"){await enemyRound(C,E,ps);if(await partyWipe(C)){C=await campaign(C.code);E=await active(C.id)}else{E=await active(C.id);E=await advance(C,E,await players(C.id))}}}ps=await players(C.id);p=ps.find(z=>z.crawler_number==b.crawlerNumber);C=await campaign(C.code);return J(200,{campaign:{...C,players:ps},player:p,event:E})}
 if(!E||E.id!=b.eventId)return J(409,{error:"The Dungeon has already moved on"});
 if(b.action==="vote"){E.payload.votes=E.payload.votes||{};E.payload.votes[String(p.crawler_number)]=Number(b.choice);await saveEvent(E)}
 if(b.action==="roll"){E.payload.results=E.payload.results||{};if(!E.payload.results[String(p.crawler_number)]){let stat=E.payload.stat||"Wisdom",roll=1+Math.floor(Math.random()*20),modifier=mod(p.profile,stat),total=roll+modifier,success=total>=Number(E.payload.dc||12);E.payload.results[String(p.crawler_number)]={stat,roll,modifier,total,success,narration:success?"You notice the danger before it decides you are part of the furniture.":"You notice the trap at exactly the moment it becomes a personal experience."};await saveEvent(E)}}
 if(b.action==="act"){E.payload.acted=E.payload.acted||{};if(E.payload.acted[String(p.crawler_number)])return J(409,{error:"Action already recorded"});if(b.actionType==="defend"){await q(`game_players?id=eq.${p.id}`,{method:"PATCH",body:JSON.stringify({defended:true})});E.payload.log.push(`${p.crawler_name} protects the parts they are emotionally attached to.`)}else{let stat=b.actionType==="ability"?"Charisma":b.actionType==="improvise"?"Intelligence":"Strength",bonus=b.actionType==="ability"?2:b.actionType==="improvise"?1:0,roll=1+Math.floor(Math.random()*20),hit=roll+mod(p.profile,stat)+bonus>=E.payload.enemy.ac,damage=hit?Math.max(1,1+Math.floor(Math.random()*8)+Math.max(0,mod(p.profile,stat))):0;if(hit)E.payload.enemy.hp=Math.max(0,E.payload.enemy.hp-damage);let verbs={attack:"meets the boss head-on",ability:"weaponizes their classification",improvise:"turns the room into a weapon"};E.payload.log.push(`${p.crawler_name} ${verbs[b.actionType]||"acts"}: ${hit?damage+" damage":"the Dungeon records an educational miss"}.`)}E.payload.acted[String(p.crawler_number)]=true;await saveEvent(E);await enemyRound(C,E,await players(C.id));await partyWipe(C)}
 if(b.action==="claim"){let claimed=E.payload.claimedBy||[];if(!claimed.includes(Number(p.crawler_number))){let inv=Array.isArray(p.inventory)?p.inventory:[];inv.push(E.payload.item);await q(`game_players?id=eq.${p.id}`,{method:"PATCH",body:JSON.stringify({inventory:inv,gold:Number(p.gold||0)+25})});claimed.push(Number(p.crawler_number));E.payload.claimedBy=claimed;await saveEvent(E)}}
 return J(200,{ok:true})
 }catch(err){console.error(err);return J(500,{error:"Dungeon processing failed: "+String(err.message).slice(0,180)})}}
