const QUESTIONS = [
  ['creature','A dangerous creature is trapped beneath rubble. A child is being chased nearby. What do you do first, and why?'],
  ['loot','You and a stranger find one life-saving item. The stranger insists they need it more. What happens next?'],
  ['curse','Choose a permanent price for extraordinary power: pain, lost memories, unwanted truth, or refusal. Explain your choice.'],
  ['betrayal','A trusted party member betrays you, but their information could still save the group. What do you do?'],
  ['boss','The final boss is stronger than your entire party. You have one hour before combat. How do you prepare?']
];
const KEYWORDS={bond:['tame','befriend','animal','creature','calm','trust','help'],protect:['save','protect','child','group','party','everyone','both'],strategy:['plan','examine','information','prepare','option','use','benefit','trap'],social:['convince','agree','negotiate','talk','offer','persuade','deal'],survival:['survive','escape','live','safe','risk'],adapt:['remade','adapt','change','future','rebuild','learn'],risk:['curse','pain','sacrifice','cost','price'],identity:['memory','identity','past','self','become'],control:['control','leverage','watch','contain','restrain'],knowledge:['learn','study','research','weakness','pattern'],leadership:['assign','team','lead','roles','coordinate']};
const ARCHETYPES=[
{title:'The Better Offer',type:'Controller / Support',className:'Beast Diplomat',race:'Serpentkin',alignment:'Chaotic Cooperative',primary:['social','bond','strategy'],quote:'The dungeon does not need another weapon. It needs a negotiator.'},
{title:'The Last Door Standing',type:'Defender / Commander',className:'Oath Warden',race:'Ironblood',alignment:'Protective Neutral',primary:['protect','leadership','survival'],quote:'Anything behind me is not yours to take.'},
{title:'The Unwritten Option',type:'Tactician / Manipulator',className:'Loophole Architect',race:'Mirrorborn',alignment:'Chaotic Strategic',primary:['strategy','control','knowledge'],quote:'Your rules are only dangerous when I agree they are rules.'},
{title:'The One Who Returned',type:'Adaptive / Skirmisher',className:'Ruinwalker',race:'Ashborn',alignment:'Pragmatic Neutral',primary:['adapt','survival','risk'],quote:'Meaning can be rebuilt. So can I.'}
];
const state={step:'welcome',name:'',question:0,answers:{},profile:null};
const app=document.querySelector('#app');
const escapeHtml=s=>s.replace(/[&<>'"]/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;',"'":'&#39;','"':'&quot;'}[c]));
function scoreAnswers(answers){const scores=Object.fromEntries(Object.keys(KEYWORDS).map(k=>[k,0]));Object.values(answers).forEach(answer=>{const text=answer.toLowerCase();for(const[tag,words]of Object.entries(KEYWORDS))words.forEach(word=>{if(text.includes(word))scores[tag]+=2});if(/both|third option|another way|instead/.test(text))scores.strategy+=4;if(/convince|negotiate|offer|agree/.test(text))scores.social+=3;if(/save|protect|child|party/.test(text))scores.protect+=3});return scores}
function buildProfile(name,answers,crawlerNumber){const scores=scoreAnswers(answers);const ranked=Object.entries(scores).sort((a,b)=>b[1]-a[1]);const archetype=ARCHETYPES.map(a=>({...a,score:a.primary.reduce((sum,key)=>sum+(scores[key]||0),0)})).sort((a,b)=>b.score-a.score)[0];const top=ranked.slice(0,3).map(([k])=>k);const stat=(base,keys)=>Math.min(18,base+keys.reduce((s,k)=>s+Math.floor((scores[k]||0)/5),0));return{name,crawlerNumber,...archetype,stats:{Strength:stat(6,['protect','survival']),Dexterity:stat(7,['adapt','risk']),Constitution:stat(7,['survival','protect']),Intelligence:stat(10,['strategy','knowledge']),Wisdom:stat(10,['bond','adapt','identity']),Charisma:stat(10,['social','leadership'])},traits:[top.includes('bond')?'Monster Whisperer':'Threat Reader',top.includes('strategy')?'False Choice':'Pressure Tested',top.includes('social')?'Better Offer':'Adaptive Mind'],weakness:top.includes('protect')?'You will endanger yourself for those you claim as yours.':'You trust your own plan long after sensible people begin screaming.',threat:archetype.score>20?'HIGH':'MODERATE'}}
async function allocateNumber(){try{const r=await fetch('/.netlify/functions/allocate-crawler-number',{method:'POST'});if(!r.ok)throw new Error();return(await r.json()).crawlerNumber}catch{return Math.floor(Math.random()*13000000)+1}}
function reaction(answer){const scores=scoreAnswers({a:answer});const top=Object.entries(scores).sort((a,b)=>b[1]-a[1]).slice(0,2).map(([k])=>k);const line=answer.toLowerCase().match(/both|another way|instead|convince|negotiate/)?'ERROR: SUBJECT HAS ONCE AGAIN REFUSED TO RESPECT THE WRITER’S FALSE CHOICE. Management is irritated. The audience is interested.':'Response recorded. The audience has begun making irresponsible financial decisions based on your survival odds.';return{line,tags:top}}
function render(){if(state.step==='welcome')return renderWelcome();if(state.step==='quiz')return renderQuiz();return renderReveal()}
function renderWelcome(){app.innerHTML=`<section class="panel welcome"><p class="eyebrow">MANDATORY SURVIVAL CLASSIFICATION</p><h1>CRAWLER<br><span>INTAKE</span></h1><p class="lede">Your former life has been successfully converted into entertainment. Complete the assessment. Receive a permanent crawler number from 1 to 13,000,000. Try not to embarrass your species.</p><label>Crawler name<input id="name" placeholder="Enter designation" maxlength="40"></label><button id="begin" disabled>ENTER THE DUNGEON</button><small>Unofficial fan-made personality generator. Not affiliated with any author, publisher, or rights holder.</small></section>`;const input=document.querySelector('#name'),button=document.querySelector('#begin');input.addEventListener('input',()=>button.disabled=!input.value.trim());input.addEventListener('keydown',e=>{if(e.key==='Enter'&&input.value.trim())begin(input.value)});button.onclick=()=>begin(input.value)}
function begin(name){state.name=name.trim();state.step='quiz';render()}
function renderQuiz(){const [id,prompt]=QUESTIONS[state.question],progress=((state.question+1)/QUESTIONS.length)*100;app.innerHTML=`<section class="panel quiz"><div class="progress"><span style="width:${progress}%"></span></div><p class="eyebrow">PSYCHOLOGICAL ASSESSMENT ${state.question+1}/${QUESTIONS.length}</p><h2>${prompt}</h2><textarea id="answer" placeholder="The Dungeon AI is listening..." rows="8"></textarea><div id="reaction"></div><div class="ai-note">SYSTEM NOTE: Attempts to reject the available choices will be recorded. Unfortunately for management, they may also be rewarded.</div><button id="submit" disabled>${state.question===QUESTIONS.length-1?'COMPLETE ASSESSMENT':'SUBMIT RESPONSE'}</button></section>`;const a=document.querySelector('#answer'),b=document.querySelector('#submit');a.addEventListener('input',()=>b.disabled=!a.value.trim());b.onclick=()=>submit(id,a.value,b)}
async function submit(id,value,button){state.answers[id]=value.trim();const r=reaction(value);document.querySelector('#reaction').innerHTML=`<div class="reaction"><b>DUNGEON AI:</b> ${r.line}<div class="tag-row">${r.tags.map(t=>`<span class="tag">${t.toUpperCase()} DETECTED</span>`).join('')}</div></div>`;button.disabled=true;if(state.question<QUESTIONS.length-1){setTimeout(()=>{state.question++;render()},650);return}button.textContent='ASSIGNING CRAWLER NUMBER…';const crawlerNumber=await allocateNumber();state.profile=buildProfile(state.name,state.answers,crawlerNumber);state.step='reveal';render()}
function traitText(t){return t==='False Choice'?'You instinctively notice options the Dungeon hoped you would ignore.':t==='Monster Whisperer'?'Hostile creatures hesitate before deciding whether you are food, friend, or management.':'You gain leverage by understanding what others need.'}
function renderReveal(){const p=state.profile;app.innerHTML=`<section class="reveal-wrap"><div class="card" id="crawler-card"><header><div><p class="eyebrow">OFFICIAL CRAWLER DOSSIER</p><h2>${escapeHtml(p.name)}</h2><h3>“${p.title}”</h3></div><div class="number"><span>CRAWLER</span><strong>#${p.crawlerNumber.toLocaleString()}</strong></div></header><div class="classification"><b>${p.type}</b><span>${p.alignment}</span><em>THREAT: ${p.threat}</em></div><div class="grid"><section><h4>ATTRIBUTES</h4>${Object.entries(p.stats).map(([k,v])=>`<div class="stat"><span>${k}</span><b>${v}</b></div>`).join('')}</section><section><h4>STARTING TRAITS</h4>${p.traits.map(t=>`<div class="trait"><b>${t}</b><p>${traitText(t)}</p></div>`).join('')}</section></div><div class="path"><div><span>RACE AFFINITY</span><b>${p.race}</b></div><div><span>CLASS CANDIDATE</span><b>${p.className}</b></div></div><blockquote>${p.quote}</blockquote><div class="weakness"><b>EXPLOITABLE FLAW:</b> ${p.weakness}</div><footer>PROPERTY OF THE DUNGEON • REGISTRATION NUMBER PERMANENT</footer></div><div class="actions"><button id="download">DOWNLOAD CRAWLER CARD</button><button class="secondary" id="again">CREATE ANOTHER</button></div></section>`;document.querySelector('#download').onclick=downloadCard;document.querySelector('#again').onclick=()=>location.reload()}
async function downloadCard(){const card=document.querySelector('#crawler-card');if(!window.html2canvas){alert('Image export library did not load. Please check your connection.');return}const canvas=await window.html2canvas(card,{scale:2,backgroundColor:'#efe3ca'});const link=document.createElement('a');link.download=`${state.profile.name.replace(/\s+/g,'-').toLowerCase()}-crawler-${state.profile.crawlerNumber}.png`;link.href=canvas.toDataURL('image/png');link.click()}
render();
