const app=document.querySelector("#app");
const s={key:sessionStorage.getItem("dungeonos_admin_key")||"",campaign:null,campaigns:[],event:null,timer:null};
const e=(v="")=>String(v)
  .replaceAll("&","&amp;")
  .replaceAll("<","&lt;")
  .replaceAll(">","&gt;")
  .replaceAll('"',"&quot;")
  .replaceAll("'","&#39;");
async function api(action,x={}){let r=await fetch("/.netlify/functions/game-admin-api",{method:"POST",headers:{"Content-Type":"application/json","X-Dungeon-Admin-Key":s.key},body:JSON.stringify({action,...x})}),d=await r.json().catch(()=>({}));if(!r.ok)throw Error(d.error||"Admin action failed.");return d}
function login(err=""){clearInterval(s.timer);app.innerHTML=`<section class="panel login"><h1>GAME MASTER<br>CONSOLE</h1>${err?`<p>${e(err)}</p>`:""}<input id="k" type="password" placeholder="Administrator key"><button id="go">Authorize</button></section>`;go.onclick=async()=>{s.key=k.value.trim();try{await api("status");sessionStorage.setItem("dungeonos_admin_key",s.key);refresh();s.timer=setInterval(refresh,3000)}catch(x){login(x.message)}}}
async function refresh(){try{let d=await api("dashboard",{campaignCode:s.campaign?.code});s.campaigns=d.campaigns||s.campaigns;if(d.campaign)s.campaign=d.campaign;if(d.event!==undefined)s.event=d.event;render()}catch(x){console.error(x)}}
function top(x){app.innerHTML=`<header class="top"><div class="logo">DUNGEON<span>OS</span></div><b>GAME MASTER</b></header>${x}`}
function render(){if(!s.key)return login();if(!s.campaign)return lobby();let c=s.campaign,ev=s.event;top(`<div class="grid"><aside><section class="panel"><h3>Campaign</h3><div class="code">${e(c.code)}</div><b>${e(c.name)}</b><p>Floor ${c.floor} • ${e(c.status)}</p><button id="copy">Copy Player Link</button><button class="alt" id="back">Campaign List</button></section><section class="panel"><h3>Crawlers</h3><div class="party">${(c.players||[]).map(p=>`<div>${e(p.crawler_name)} <b>${p.hp}/${p.max_hp} HP</b></div>`).join("")||"Waiting..."}</div></section></aside><main><section class="panel"><h2>Live Control</h2><div class="controls"><button id="begin">Begin Floor</button><button class="alt" id="heal">Heal Party</button><button id="enemy">Enemy Turn</button></div></section><section class="panel"><h2>Current Event</h2>${ev?`<div class="event"><h3>${e(ev.payload?.title||ev.payload?.enemy?.name||ev.type)}</h3><p>${e(ev.payload?.text||ev.payload?.enemy?.description||"")}</p></div>`:"<p>No active event.</p>"}</section><section class="panel"><h2>Tutorial Floor</h2><div class="script">${steps(c.script_step||0)}</div></section></main></div>`);copy.onclick=()=>navigator.clipboard.writeText(location.origin+"/play");back.onclick=()=>{s.campaign=null;s.event=null;render()};begin.onclick=()=>run(0);heal.onclick=async()=>{await api("heal",{campaignCode:c.code});refresh()};enemy.onclick=async()=>{if(!ev)return;await api("enemy",{campaignCode:c.code,eventId:ev.id});refresh()};document.querySelectorAll("[data-step]").forEach(b=>b.onclick=()=>run(Number(b.dataset.step)))}
function lobby(){top(`<section class="panel"><h1>CREATE<br>CAMPAIGN</h1><input id="name" value="Tutorial Guild"><button id="create">Create Game Night</button></section><section class="panel"><h2>Existing Campaigns</h2>${s.campaigns.map(c=>`<div class="campaign" data-code="${c.code}"><div class="code">${e(c.code)}</div>${e(c.name)}</div>`).join("")||"<p>None yet.</p>"}</section>`);create.onclick=async()=>{let d=await api("create",{name:name.value.trim()});s.campaign=d.campaign;render()};document.querySelectorAll("[data-code]").forEach(b=>b.onclick=async()=>{let d=await api("dashboard",{campaignCode:b.dataset.code});s.campaign=d.campaign;s.event=d.event;render()})}
const S=["Floor One Initialization","The Crushed Station","Choose the First Door","The Tripwire Hall","The Nursery of Teeth","Boss: Customer Service Representative","The Complaint Box","Floor One Complete"];function steps(n){return S.map((x,i)=>`<div class="step"><b>${i+1}</b><span>${e(x)}</span><button data-step="${i}" ${i<n?"disabled":""}>Run</button></div>`).join("")}async function run(step){let d=await api("step",{campaignCode:s.campaign.code,step});s.campaign=d.campaign;s.event=d.event;render()}if(s.key){refresh();s.timer=setInterval(refresh,3000)}else login();