const app=document.querySelector("#app");
const save=JSON.parse(localStorage.getItem("dungeonPlayer")||"null");
const s={code:save?.code||"",num:save?.num||"",player:null,campaign:null,event:null,timer:null};
const e=(v="")=>String(v)
  .replaceAll("&","&amp;")
  .replaceAll("<","&lt;")
  .replaceAll(">","&gt;")
  .replaceAll('"',"&quot;")
  .replaceAll("'","&#39;");
async function api(action,x={}){const r=await fetch("/.netlify/functions/game-api",{method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify({action,...x})});const d=await r.json().catch(()=>({}));if(!r.ok)throw Error(d.error||"Dungeon connection failed.");return d}
function join(err=""){clearInterval(s.timer);app.innerHTML=`<section class="panel"><h1>JOIN THE<br><span>DUNGEON</span></h1>${err?`<p>${e(err)}</p>`:""}<label>Campaign code<input id="c" value="${e(s.code)}"></label><label>Crawler number<input id="n" inputmode="numeric" value="${e(s.num)}"></label><button id="go">Connect Crawler</button></section>`;go.onclick=async()=>{try{let code=c.value.trim().toUpperCase(),num=Number(n.value.replace(/\D/g,""));let d=await api("join",{campaignCode:code,crawlerNumber:num});Object.assign(s,{code,num,player:d.player,campaign:d.campaign,event:d.event});localStorage.setItem("dungeonPlayer",JSON.stringify({code,num}));render();poll()}catch(x){join(x.message)}}}
function poll(){clearInterval(s.timer);refresh();s.timer=setInterval(refresh,3000)}
async function refresh(){try{let d=await api("state",{campaignCode:s.code,crawlerNumber:Number(s.num)});Object.assign(s,{player:d.player,campaign:d.campaign,event:d.event});render()}catch(x){join(x.message)}}
function head(){let p=s.player,h=p?.hp||0,m=p?.max_hp||1;return `<div class="status"><div><div class="num">Crawler #${Number(s.num).toLocaleString()}</div><b>${e(p?.crawler_name||"Connecting")}</b></div><div class="hp">HP ${h}/${m}<div class="bar"><i style="width:${Math.max(0,Math.min(100,h/m*100))}%"></i></div></div></div>`}
function render(){if(!s.player||!s.campaign){app.innerHTML=`<section class="panel waiting"><h2>CONNECTING</h2><div class="pulse"></div></section>`;return}let ev=s.event,b="";if(s.campaign.status==="waiting"&&!ev){b=`<section class="panel waiting"><h2>WAITING ROOM</h2><p>Campaign <b>${e(s.code)}</b></p><div class="pulse"></div><div class="party">${(s.campaign.players||[]).map(p=>`<div><span>${e(p.crawler_name)}</span><b>#${p.crawler_number}</b></div>`).join("")}</div></section>`}else if(!ev)b=`<section class="panel waiting"><h2>WAITING FOR THE DUNGEON</h2><div class="pulse"></div></section>`;else b=eventView(ev);app.innerHTML=head()+b;wire(ev)}
function eventView(ev){let p=ev.payload||{};if(ev.type==="broadcast")return `<section class="panel"><div class="broadcast"><b>ATTENTION, CRAWLERS</b><h2>${e(p.title)}</h2><p>${e(p.text)}</p></div></section>`;if(ev.type==="narration")return `<section class="panel"><h2>${e(p.title)}</h2><p>${e(p.text)}</p></section>`;if(ev.type==="choice"){let v=p.votes?.[String(s.num)];return `<section class="panel"><h2>${e(p.title)}</h2><p>${e(p.text)}</p><div class="choices">${(p.options||[]).map((o,i)=>`<button class="${Number(v)===i?"sel":""}" data-choice="${i}">${String.fromCharCode(65+i)}. ${e(o)}</button>`).join("")}</div></section>`}if(ev.type==="check"){let r=p.results?.[String(s.num)];return `<section class="panel"><h2>${e(p.title)}</h2><p>${e(p.text)}</p>${r?`<div class="result"><span>${e(r.stat)} Check</span><strong>${r.total}</strong><p>${r.success?"SUCCESS":"FAILURE"}</p></div>`:`<button id="roll">Roll ${e(p.stat)}</button>`}</section>`}if(ev.type==="combat"){let en=p.enemy||{};return `<section class="panel"><h2>${e(en.name)}</h2><p>${e(en.description)}</p><div class="card">Enemy HP ${en.hp}/${en.maxHp}</div>${s.player.hp>0&&en.hp>0?`<div class="combat"><button data-act="attack">Attack</button><button class="alt" data-act="defend">Defend</button><button data-act="ability">Class Ability</button><button class="alt" data-act="improvise">Improvise</button></div>`:""}<div class="log">${(p.log||[]).slice(-12).reverse().map(x=>`<p>${e(x)}</p>`).join("")}</div></section>`}if(ev.type==="loot"){let got=(p.claimedBy||[]).includes(Number(s.num));return `<section class="panel"><h2>${e(p.title)}</h2><div class="loot"><span>${e(p.rarity)}</span><strong>${e(p.item?.name)}</strong><p>${e(p.item?.description)}</p></div>${got?"<p>ITEM ADDED TO INVENTORY</p>":`<button id="claim">Claim Loot</button>`}</section>`}return `<section class="panel"><div class="broadcast"><b>FLOOR COMPLETE</b><h2>${e(p.title)}</h2><p>${e(p.text)}</p></div></section>`}
function wire(ev){if(!ev)return;document.querySelectorAll("[data-choice]").forEach(b=>b.onclick=async()=>{b.disabled=true;await api("vote",{campaignCode:s.code,crawlerNumber:Number(s.num),eventId:ev.id,choice:Number(b.dataset.choice)});refresh()});if(document.querySelector("#roll"))roll.onclick=async()=>{roll.disabled=true;await api("roll",{campaignCode:s.code,crawlerNumber:Number(s.num),eventId:ev.id});refresh()};document.querySelectorAll("[data-act]").forEach(b=>b.onclick=async()=>{b.disabled=true;await api("act",{campaignCode:s.code,crawlerNumber:Number(s.num),eventId:ev.id,actionType:b.dataset.act});refresh()});if(document.querySelector("#claim"))claim.onclick=async()=>{claim.disabled=true;await api("claim",{campaignCode:s.code,crawlerNumber:Number(s.num),eventId:ev.id});refresh()}}
if(s.code&&s.num)poll();else join();