create table if not exists public.crawler_numbers (
  id bigint generated by default as identity primary key,
  crawler_number integer not null unique check (crawler_number between 1 and 13000000),
  created_at timestamptz not null default now()
);

alter table public.crawler_numbers enable row level security;
-- No public policies are needed. The Netlify function uses the service-role key.
