create table if not exists public.crawler_profiles (
  id bigint generated by default as identity primary key,
  crawler_number integer not null unique
    check (crawler_number between 1 and 13000000),
  crawler_name text not null,
  profile jsonb not null,
  created_at timestamptz not null default now()
);

alter table public.crawler_profiles enable row level security;

create index if not exists crawler_profiles_number_idx
  on public.crawler_profiles (crawler_number);
