-- DungeonOS v1 complete database setup
-- Safe to run more than once.

create table if not exists public.crawler_profiles (
  id bigint generated by default as identity primary key,
  crawler_number integer not null unique
    check (crawler_number between 1 and 13000000),
  crawler_name text not null,
  profile jsonb not null,
  created_at timestamptz not null default now()
);

create table if not exists public.game_campaigns (
  id bigint generated by default as identity primary key,
  code text not null unique,
  name text not null,
  status text not null default 'waiting',
  floor integer not null default 1,
  script_step integer not null default 0,
  director_state jsonb not null default '{
    "mode":"idle",
    "beatIndex":0,
    "paused":false,
    "tone":{"tension":55,"danger":45,"humor":55},
    "flags":{},
    "history":[]
  }'::jsonb,
  created_at timestamptz not null default now()
);

create table if not exists public.game_players (
  id bigint generated by default as identity primary key,
  campaign_id bigint not null references public.game_campaigns(id) on delete cascade,
  crawler_number integer not null,
  crawler_name text not null,
  profile jsonb not null,
  hp integer not null,
  max_hp integer not null,
  inventory jsonb not null default '[]'::jsonb,
  defended boolean not null default false,
  story_flags jsonb not null default '{}'::jsonb,
  conditions jsonb not null default '[]'::jsonb,
  gold integer not null default 0,
  joined_at timestamptz not null default now(),
  unique(campaign_id, crawler_number)
);

create table if not exists public.game_events (
  id bigint generated by default as identity primary key,
  campaign_id bigint not null references public.game_campaigns(id) on delete cascade,
  type text not null,
  payload jsonb not null default '{}'::jsonb,
  active boolean not null default true,
  resolves_at timestamptz,
  created_at timestamptz not null default now()
);

alter table public.game_campaigns
  add column if not exists director_state jsonb not null default '{
    "mode":"idle",
    "beatIndex":0,
    "paused":false,
    "tone":{"tension":55,"danger":45,"humor":55},
    "flags":{},
    "history":[]
  }'::jsonb;

alter table public.game_players
  add column if not exists story_flags jsonb not null default '{}'::jsonb;
alter table public.game_players
  add column if not exists conditions jsonb not null default '[]'::jsonb;
alter table public.game_players
  add column if not exists gold integer not null default 0;
alter table public.game_events
  add column if not exists resolves_at timestamptz;

alter table public.crawler_profiles enable row level security;
alter table public.game_campaigns enable row level security;
alter table public.game_players enable row level security;
alter table public.game_events enable row level security;

create index if not exists crawler_profiles_number_idx
  on public.crawler_profiles(crawler_number);
create index if not exists game_players_campaign_idx
  on public.game_players(campaign_id);
create index if not exists game_events_campaign_active_idx
  on public.game_events(campaign_id, active);
create index if not exists game_events_resolution_idx
  on public.game_events(campaign_id, active, resolves_at);
